# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: /blog/:categories/:title/

# Setup
title: Vinay Gopinath
tagline: 'Adventures with technology and travel'
description: 'Adventures with technology and travel'
live_url: 'https://vinaygopinath.me'

# About/contact
author:
name:              Vinay Gopinath
email:             vinay@vinaygopinath.me

# Custom vars
version:             1.0.0
gems:                ["octopress-paginate", "jekyll-redirect-from"]
include: ["_pages"]
exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "_drafts"]
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

pagination:
  limit: 10
  per_page: 5
  permalink: /:num/

sass:
  sass_dir: public/styles
  style: compressed

defaults:
  -
    scope:
      path: ""
    values:
      description: "Vinay Gopinath's occasionally updated corner of the Internet"
